spring:

  ## 시간대 기준을 서울로 설정
  jackson:
    time-zone: Asia/Seoul

  ## PostgreSQL 연동
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Seoul

  data:

    ## MongoDB 연동
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_URL}/${MONGODB_DATABASE}?authSource=${MONGODB_DATABASE}

    ## Redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 4
          max-wait: 5000ms
          max-idle: 4
          min-idle: 0

  ## OAuth 설정
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: profile, email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

          apple:
            client-id: ${APPLE_WEB_CLIENT_ID}
            client-secret: /home/ec2-user/secrets/${APPLE_CLIENT_SECRET}
            redirect-uri: ${APPLE_REDIRECT_URI}
            client-name: Apple Web
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token

  ## S3 Cloud 설정
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      cloudfront:
        domain: ${AWS_CLOUDFRONT_DOMAIN}

## 파일 업로드 설정
file:
  upload:
    max-size: 3145728
    allowed-extensions: jpg,jpeg,png,webp

## Spring Security 로그 설정
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client.endpoint: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

## Firebase 설정
firebase:
  config:
    path: firebase/repicka-firebase-adminsdk.json