name: CI/CD with github actions & docker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DOCKER_IMAGE: ghcr.io/kyeahxx19/repicka:latest

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # PR이나 push일 때 Test 실행
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: repicka_test
          POSTGRES_USER: ${{ secrets.TEST_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432

      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.TEST_MONGODB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.TEST_MONGODB_PASSWORD }}

    env:
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
      TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
      TEST_MONGODB_USERNAME: ${{ secrets.TEST_MONGODB_USERNAME }}
      TEST_MONGODB_PASSWORD: ${{ secrets.TEST_MONGODB_PASSWORD }}
      TEST_MONGODB_DATABASE: ${{ secrets.TEST_MONGODB_DATABASE }}
      JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      FRONTEND_URI: ${{ secrets.TEST_FRONTEND_URI }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean test

  build:
    needs: test
    runs-on: ubuntu-latest
    # develop 브랜치에 push될 때만 Docker Build 실행
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kyeahxx19
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          # 별도의 캐시 태그 사용으로 메인 이미지와 캐시 분리
          cache-from: type=registry,ref=ghcr.io/kyeahxx19/repicka:buildcache
          cache-to: type=registry,ref=ghcr.io/kyeahxx19/repicka:buildcache,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    # develop 브랜치에 push될 때만 Docker Deploy 실행
    if: github.event_name == 'push'
    
    steps:
      - name: Create .env
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
          echo "FRONTEND_URI=${{ secrets.FRONTEND_URI }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env
          echo "AWS_CLOUDFRONT_DOMAIN=${{ secrets.AWS_CLOUDFRONT_DOMAIN }}" >> .env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> .env
          echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> .env

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u kyeahxx19 --password-stdin

      - name: Pull latest Docker image
        run: docker pull ${{ env.DOCKER_IMAGE }}

      - name: Stop existing container (if any)
        run: |
          docker stop repicka || true
          docker rm repicka || true

      - name: Run new container
        run: |
          docker run -d \
          --network host \
          --env-file .env \
          --name repicka \
          ${{ env.DOCKER_IMAGE }} 