name: CI/CD with github actions & docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: ghcr.io/kyeahxx19/repicka:main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # PR이나 push일 때 Test 실행
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: repicka_test
          POSTGRES_USER: ${{ secrets.TEST_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432

      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.TEST_MONGODB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.TEST_MONGODB_PASSWORD }}

      redis:
        image: redis:7
        ports:
          - 6379:6379
        env:
          REDIS_HOST: ${{ secrets.MAIN_REDIS_HOST }}
          REDIS_PORT: ${{ secrets.MAIN_REDIS_PORT }}

    env:
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
      TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
      TEST_MONGODB_USERNAME: ${{ secrets.TEST_MONGODB_USERNAME }}
      TEST_MONGODB_PASSWORD: ${{ secrets.TEST_MONGODB_PASSWORD }}
      TEST_MONGODB_DATABASE: ${{ secrets.TEST_MONGODB_DATABASE }}
      REDIS_HOST: ${{ secrets.MAIN_REDIS_HOST }}
      REDIS_PORT: ${{ secrets.MAIN_REDIS_PORT }}
      JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      FRONTEND_URI: ${{ secrets.TEST_FRONTEND_URI }}
      APPLE_WEB_CLIENT_ID: ${{ secrets.APPLE_WEB_CLIENT_ID }}
      APPLE_APP_CLIENT_ID: ${{ secrets.APPLE_APP_CLIENT_ID }}
      APPLE_CLIENT_SECRET: ${{ secrets.APPLE_CLIENT_SECRET }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_REDIRECT_URI: ${{ secrets.APPLE_REDIRECT_URI }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Restore Firebase Admin SDK file
        run: |
          mkdir -p ./src/main/resources/firebase
          echo "${{ secrets.FIREBASE_ADMIN_JSON }}" | base64 -d > ./src/main/resources/firebase/repicka-firebase-adminsdk.json

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean test

  build:
    needs: test
    runs-on: ubuntu-latest
    # 브랜치에 push될 때만 Docker Build 실행
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Restore Firebase Admin SDK file
        run: |
          mkdir -p ./src/main/resources/firebase
          echo "${{ secrets.FIREBASE_ADMIN_JSON }}" | base64 -d > ./src/main/resources/firebase/repicka-firebase-adminsdk.json
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kyeahxx19
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          # 별도의 캐시 태그 사용으로 메인 이미지와 캐시 분리
          cache-from: type=registry,ref=ghcr.io/kyeahxx19/repicka:buildcache
          cache-to: type=registry,ref=ghcr.io/kyeahxx19/repicka:buildcache,mode=max

  deploy:
    needs: build
    runs-on: [self-hosted, main]
    # 브랜치에 push될 때만 Docker Deploy 실행
    if: github.event_name == 'push'
    
    steps:
      - name: Create .env
        run: |
          echo "DB_URL=${{ secrets.MAIN_DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.MAIN_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.MAIN_DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.MAIN_JWT_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
          echo "APPLE_WEB_CLIENT_ID=${{ secrets.APPLE_WEB_CLIENT_ID }}" >> .env
          echo "APPLE_APP_CLIENT_ID=${{ secrets.APPLE_APP_CLIENT_ID }}" >> .env
          echo "APPLE_CLIENT_SECRET=${{ secrets.APPLE_CLIENT_SECRET }}" >> .env
          echo "APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }}" >> .env
          echo "APPLE_REDIRECT_URI=${{ secrets.APPLE_REDIRECT_URI }}" >> .env
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> .env
          echo "FRONTEND_URI=${{ secrets.MAIN_FRONTEND_URI }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.MAIN_AWS_REGION }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.MAIN_AWS_S3_BUCKET_NAME }}" >> .env
          echo "AWS_CLOUDFRONT_DOMAIN=${{ secrets.MAIN_AWS_CLOUDFRONT_DOMAIN }}" >> .env
          echo "MONGODB_URL=${{ secrets.MAIN_MONGODB_URL }}" >> .env
          echo "MONGODB_USERNAME=${{ secrets.MAIN_MONGODB_USERNAME }}" >> .env
          echo "MONGODB_PASSWORD=${{ secrets.MAIN_MONGODB_PASSWORD }}" >> .env
          echo "MONGODB_DATABASE=${{ secrets.MAIN_MONGODB_DATABASE }}" >> .env
          echo "REDIS_HOST=${{ secrets.MAIN_REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.MAIN_REDIS_PORT }}" >> .env

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u kyeahxx19 --password-stdin

      - name: Pull latest Docker image
        run: sudo docker pull ${{ env.DOCKER_IMAGE }}

      - name: Stop existing container (if any)
        run: |
          sudo docker stop repicka || true
          sudo docker rm repicka || true

      - name: Run new container
        run: |
          sudo docker run -d \
          --network host \
          --env-file .env \
          -v /home/ec2-user/secrets:/app/secrets:ro \
          --user 1000:1000 \
          -e APPLE_WEB_CLIENT_ID=${{ secrets.APPLE_WEB_CLIENT_ID }} \
          -e APPLE_APP_CLIENT_ID=${{ secrets.APPLE_APP_CLIENT_ID }} \
          -e APPLE_CLIENT_SECRET=${{ secrets.APPLE_CLIENT_SECRET }} \
          -e APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }} \
          -e APPLE_REDIRECT_URI=${{ secrets.APPLE_REDIRECT_URI }} \
          -e APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }} \
          --name repicka \
          ${{ env.DOCKER_IMAGE }}