name: Spring Boot Test CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: repicka_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    env:
      TEST_DB_URL: jdbc:postgresql://localhost:5432/repicka_test
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: password

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean test